/**
 * Swagger Customer - OpenAPI 3.0
 *
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const AccountStatusEnum = {
    Active: 'ACTIVE',
    Inactive: 'INACTIVE',
    Closed: 'CLOSED'
} as const;
export type AccountStatusEnum = typeof AccountStatusEnum[keyof typeof AccountStatusEnum];

