/**
 * Swagger Customer - OpenAPI 3.0
 *
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountStatusEnum } from './accountStatusEnum';
import { PaginationRequest } from './paginationRequest';
import { AccountTypeEnum } from './accountTypeEnum';


export interface BankAccountFilterRequest { 
    firstName?: string;
    lastName?: string;
    phone?: string;
    email?: string;
    accountNumber?: string;
    accountType?: AccountTypeEnum;
    ifscCode?: string;
    status?: AccountStatusEnum;
    pagination?: PaginationRequest;
}
export namespace BankAccountFilterRequest {
}


