/**
 * Swagger Customer - OpenAPI 3.0
 *
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const DomainEnum = {
    Education: 'EDUCATION',
    International: 'INTERNATIONAL',
    Investments: 'INVESTMENTS',
    Medical: 'MEDICAL',
    Public: 'PUBLIC',
    Restaurant: 'RESTAURANT',
    Retail: 'RETAIL'
} as const;
export type DomainEnum = typeof DomainEnum[keyof typeof DomainEnum];

