/**
 * Swagger Customer - OpenAPI 3.0
 *
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRoleEnum } from './userRoleEnum';


export interface LoginUserResponse { 
    id?: string;
    email?: string;
    username?: string;
    name?: string;
    roles?: Array<UserRoleEnum>;
}

