/**
 * Swagger Customer - OpenAPI 3.0
 *
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SortOrderEnum } from './sortOrderEnum';


export interface PaginationRequest { 
    pageSize?: number;
    pageNumber?: number;
    sortBy?: string;
    sortOrder?: SortOrderEnum;
    previousPageToken?: number;
    nextPageToken?: number;
}
export namespace PaginationRequest {
}


