/**
 * Swagger Customer - OpenAPI 3.0
 *
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const PaymentMethodEnum = {
    Card: 'CARD',
    Cash: 'CASH',
    Upi: 'UPI'
} as const;
export type PaymentMethodEnum = typeof PaymentMethodEnum[keyof typeof PaymentMethodEnum];

