/**
 * Swagger Customer - OpenAPI 3.0
 *
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentMethodEnum } from './paymentMethodEnum';
import { DomainEnum } from './domainEnum';
import { TransactionStatusEnum } from './transactionStatusEnum';
import { PaginationRequest } from './paginationRequest';


export interface TransactionFilterRequest { 
    date?: string;
    domain?: DomainEnum;
    location?: string;
    value?: number;
    status?: TransactionStatusEnum;
    paymentMethod?: PaymentMethodEnum;
    taxAmount?: number;
    netValue?: number;
    pagination?: PaginationRequest;
}
export namespace TransactionFilterRequest {
}


